# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1206, 835)
        self.tabWidget = QtWidgets.QTabWidget(Dialog)
        self.tabWidget.setGeometry(QtCore.QRect(20, 10, 1161, 801))
        self.tabWidget.setObjectName("tabWidget")
        self.Data = QtWidgets.QWidget()
        self.Data.setObjectName("Data")
        self.save_data = QtWidgets.QPushButton(self.Data)
        self.save_data.setGeometry(QtCore.QRect(30, 490, 80, 23))
        self.save_data.setObjectName("save_data")
        self.frame = QtWidgets.QFrame(self.Data)
        self.frame.setGeometry(QtCore.QRect(30, 20, 911, 101))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.Input = QtWidgets.QGroupBox(self.frame)
        self.Input.setGeometry(QtCore.QRect(10, 10, 891, 81))
        self.Input.setObjectName("Input")
        self.label = QtWidgets.QLabel(self.Input)
        self.label.setGeometry(QtCore.QRect(20, 40, 51, 25))
        self.label.setObjectName("label")
        self.data_x = QtWidgets.QTextEdit(self.Input)
        self.data_x.setGeometry(QtCore.QRect(80, 40, 301, 25))
        self.data_x.setObjectName("data_x")
        self.frame_2 = QtWidgets.QFrame(self.Data)
        self.frame_2.setGeometry(QtCore.QRect(30, 140, 911, 201))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.Blurring = QtWidgets.QGroupBox(self.frame_2)
        self.Blurring.setGeometry(QtCore.QRect(10, 10, 881, 171))
        self.Blurring.setObjectName("Blurring")
        self.label_2 = QtWidgets.QLabel(self.Blurring)
        self.label_2.setGeometry(QtCore.QRect(20, 30, 121, 25))
        self.label_2.setObjectName("label_2")
        self.fwhm4 = QtWidgets.QCheckBox(self.Blurring)
        self.fwhm4.setGeometry(QtCore.QRect(20, 60, 85, 21))
        self.fwhm4.setChecked(True)
        self.fwhm4.setObjectName("fwhm4")
        self.fwhm5 = QtWidgets.QCheckBox(self.Blurring)
        self.fwhm5.setGeometry(QtCore.QRect(20, 80, 85, 21))
        self.fwhm5.setChecked(True)
        self.fwhm5.setObjectName("fwhm5")
        self.fwhm6 = QtWidgets.QCheckBox(self.Blurring)
        self.fwhm6.setGeometry(QtCore.QRect(20, 100, 85, 21))
        self.fwhm6.setChecked(True)
        self.fwhm6.setObjectName("fwhm6")
        self.fwhm7 = QtWidgets.QCheckBox(self.Blurring)
        self.fwhm7.setGeometry(QtCore.QRect(20, 120, 85, 21))
        self.fwhm7.setChecked(True)
        self.fwhm7.setObjectName("fwhm7")
        self.fwhm8 = QtWidgets.QCheckBox(self.Blurring)
        self.fwhm8.setGeometry(QtCore.QRect(20, 140, 85, 21))
        self.fwhm8.setChecked(True)
        self.fwhm8.setObjectName("fwhm8")
        self.frame_3 = QtWidgets.QFrame(self.Data)
        self.frame_3.setGeometry(QtCore.QRect(30, 360, 911, 121))
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.groupBox = QtWidgets.QGroupBox(self.frame_3)
        self.groupBox.setGeometry(QtCore.QRect(10, 10, 881, 101))
        self.groupBox.setObjectName("groupBox")
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(20, 30, 121, 25))
        self.label_3.setObjectName("label_3")
        self.slice1 = QtWidgets.QRadioButton(self.groupBox)
        self.slice1.setGeometry(QtCore.QRect(20, 50, 100, 21))
        self.slice1.setObjectName("slice1")
        self.slice3 = QtWidgets.QRadioButton(self.groupBox)
        self.slice3.setGeometry(QtCore.QRect(20, 70, 100, 21))
        self.slice3.setChecked(True)
        self.slice3.setObjectName("slice3")
        self.tabWidget.addTab(self.Data, "")
        self.Model = QtWidgets.QWidget()
        self.Model.setObjectName("Model")
        self.frame_4 = QtWidgets.QFrame(self.Model)
        self.frame_4.setGeometry(QtCore.QRect(30, 20, 921, 211))
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.Input_4 = QtWidgets.QGroupBox(self.frame_4)
        self.Input_4.setGeometry(QtCore.QRect(20, 10, 891, 181))
        self.Input_4.setObjectName("Input_4")
        self.frame_5 = QtWidgets.QFrame(self.Input_4)
        self.frame_5.setGeometry(QtCore.QRect(10, 30, 121, 151))
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.label_6 = QtWidgets.QLabel(self.frame_5)
        self.label_6.setGeometry(QtCore.QRect(10, 0, 101, 25))
        self.label_6.setObjectName("label_6")
        self.radioButton = QtWidgets.QRadioButton(self.frame_5)
        self.radioButton.setGeometry(QtCore.QRect(10, 30, 115, 22))
        self.radioButton.setObjectName("radioButton")
        self.radioButton_2 = QtWidgets.QRadioButton(self.frame_5)
        self.radioButton_2.setGeometry(QtCore.QRect(10, 50, 115, 22))
        self.radioButton_2.setObjectName("radioButton_2")
        self.radioButton_3 = QtWidgets.QRadioButton(self.frame_5)
        self.radioButton_3.setGeometry(QtCore.QRect(10, 70, 115, 22))
        self.radioButton_3.setChecked(True)
        self.radioButton_3.setObjectName("radioButton_3")
        self.radioButton_4 = QtWidgets.QRadioButton(self.frame_5)
        self.radioButton_4.setGeometry(QtCore.QRect(10, 90, 115, 22))
        self.radioButton_4.setObjectName("radioButton_4")
        self.radioButton_5 = QtWidgets.QRadioButton(self.frame_5)
        self.radioButton_5.setGeometry(QtCore.QRect(10, 110, 115, 22))
        self.radioButton_5.setObjectName("radioButton_5")
        self.frame_6 = QtWidgets.QFrame(self.Input_4)
        self.frame_6.setGeometry(QtCore.QRect(140, 30, 121, 151))
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.label_7 = QtWidgets.QLabel(self.frame_6)
        self.label_7.setGeometry(QtCore.QRect(10, 0, 101, 25))
        self.label_7.setObjectName("label_7")
        self.radioButton_6 = QtWidgets.QRadioButton(self.frame_6)
        self.radioButton_6.setGeometry(QtCore.QRect(10, 30, 115, 22))
        self.radioButton_6.setObjectName("radioButton_6")
        self.radioButton_7 = QtWidgets.QRadioButton(self.frame_6)
        self.radioButton_7.setGeometry(QtCore.QRect(10, 50, 115, 22))
        self.radioButton_7.setObjectName("radioButton_7")
        self.radioButton_8 = QtWidgets.QRadioButton(self.frame_6)
        self.radioButton_8.setGeometry(QtCore.QRect(10, 70, 115, 22))
        self.radioButton_8.setChecked(True)
        self.radioButton_8.setObjectName("radioButton_8")
        self.radioButton_9 = QtWidgets.QRadioButton(self.frame_6)
        self.radioButton_9.setGeometry(QtCore.QRect(10, 90, 115, 22))
        self.radioButton_9.setObjectName("radioButton_9")
        self.radioButton_10 = QtWidgets.QRadioButton(self.frame_6)
        self.radioButton_10.setGeometry(QtCore.QRect(10, 110, 115, 22))
        self.radioButton_10.setObjectName("radioButton_10")
        self.frame_7 = QtWidgets.QFrame(self.Input_4)
        self.frame_7.setGeometry(QtCore.QRect(270, 30, 131, 151))
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.label_8 = QtWidgets.QLabel(self.frame_7)
        self.label_8.setGeometry(QtCore.QRect(10, 0, 101, 25))
        self.label_8.setObjectName("label_8")
        self.checkBox = QtWidgets.QCheckBox(self.frame_7)
        self.checkBox.setGeometry(QtCore.QRect(10, 30, 96, 22))
        self.checkBox.setChecked(True)
        self.checkBox.setObjectName("checkBox")
        self.checkBox_2 = QtWidgets.QCheckBox(self.frame_7)
        self.checkBox_2.setGeometry(QtCore.QRect(10, 50, 101, 22))
        self.checkBox_2.setChecked(True)
        self.checkBox_2.setObjectName("checkBox_2")
        self.checkBox_3 = QtWidgets.QCheckBox(self.frame_7)
        self.checkBox_3.setGeometry(QtCore.QRect(10, 70, 96, 22))
        self.checkBox_3.setChecked(True)
        self.checkBox_3.setObjectName("checkBox_3")
        self.checkBox_4 = QtWidgets.QCheckBox(self.frame_7)
        self.checkBox_4.setGeometry(QtCore.QRect(10, 90, 101, 22))
        self.checkBox_4.setChecked(True)
        self.checkBox_4.setObjectName("checkBox_4")
        self.checkBox_5 = QtWidgets.QCheckBox(self.frame_7)
        self.checkBox_5.setGeometry(QtCore.QRect(10, 110, 96, 22))
        self.checkBox_5.setChecked(True)
        self.checkBox_5.setObjectName("checkBox_5")
        self.save_model = QtWidgets.QPushButton(self.Model)
        self.save_model.setGeometry(QtCore.QRect(30, 240, 80, 23))
        self.save_model.setObjectName("save_model")
        self.tabWidget.addTab(self.Model, "")
        self.Train = QtWidgets.QWidget()
        self.Train.setObjectName("Train")
        self.frame_8 = QtWidgets.QFrame(self.Train)
        self.frame_8.setGeometry(QtCore.QRect(30, 20, 661, 241))
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.Input_5 = QtWidgets.QGroupBox(self.frame_8)
        self.Input_5.setGeometry(QtCore.QRect(20, 10, 641, 211))
        self.Input_5.setObjectName("Input_5")
        self.frame_11 = QtWidgets.QFrame(self.Input_5)
        self.frame_11.setGeometry(QtCore.QRect(10, 30, 241, 181))
        self.frame_11.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_11.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_11.setObjectName("frame_11")
        self.label_11 = QtWidgets.QLabel(self.frame_11)
        self.label_11.setGeometry(QtCore.QRect(10, 0, 121, 25))
        self.label_11.setObjectName("label_11")
        self.checkBox_6 = QtWidgets.QCheckBox(self.frame_11)
        self.checkBox_6.setGeometry(QtCore.QRect(10, 30, 96, 22))
        self.checkBox_6.setChecked(True)
        self.checkBox_6.setObjectName("checkBox_6")
        self.checkBox_7 = QtWidgets.QCheckBox(self.frame_11)
        self.checkBox_7.setGeometry(QtCore.QRect(10, 50, 101, 22))
        self.checkBox_7.setChecked(True)
        self.checkBox_7.setObjectName("checkBox_7")
        self.checkBox_8 = QtWidgets.QCheckBox(self.frame_11)
        self.checkBox_8.setGeometry(QtCore.QRect(10, 70, 111, 22))
        self.checkBox_8.setChecked(True)
        self.checkBox_8.setObjectName("checkBox_8")
        self.checkBox_9 = QtWidgets.QCheckBox(self.frame_11)
        self.checkBox_9.setGeometry(QtCore.QRect(10, 90, 111, 22))
        self.checkBox_9.setChecked(True)
        self.checkBox_9.setObjectName("checkBox_9")
        self.checkBox_10 = QtWidgets.QCheckBox(self.frame_11)
        self.checkBox_10.setGeometry(QtCore.QRect(10, 110, 96, 22))
        self.checkBox_10.setChecked(True)
        self.checkBox_10.setObjectName("checkBox_10")
        self.data_x_2 = QtWidgets.QTextEdit(self.frame_11)
        self.data_x_2.setGeometry(QtCore.QRect(130, 30, 91, 22))
        self.data_x_2.setObjectName("data_x_2")
        self.data_x_3 = QtWidgets.QTextEdit(self.frame_11)
        self.data_x_3.setGeometry(QtCore.QRect(130, 50, 91, 22))
        self.data_x_3.setObjectName("data_x_3")
        self.data_x_4 = QtWidgets.QTextEdit(self.frame_11)
        self.data_x_4.setGeometry(QtCore.QRect(130, 70, 91, 22))
        self.data_x_4.setObjectName("data_x_4")
        self.data_x_5 = QtWidgets.QTextEdit(self.frame_11)
        self.data_x_5.setGeometry(QtCore.QRect(130, 90, 91, 22))
        self.data_x_5.setObjectName("data_x_5")
        self.data_x_6 = QtWidgets.QTextEdit(self.frame_11)
        self.data_x_6.setGeometry(QtCore.QRect(130, 110, 91, 22))
        self.data_x_6.setObjectName("data_x_6")
        self.checkBox_11 = QtWidgets.QCheckBox(self.frame_11)
        self.checkBox_11.setGeometry(QtCore.QRect(10, 130, 131, 22))
        self.checkBox_11.setChecked(True)
        self.checkBox_11.setObjectName("checkBox_11")
        self.checkBox_12 = QtWidgets.QCheckBox(self.frame_11)
        self.checkBox_12.setGeometry(QtCore.QRect(10, 150, 131, 22))
        self.checkBox_12.setChecked(True)
        self.checkBox_12.setObjectName("checkBox_12")
        self.frame_12 = QtWidgets.QFrame(self.frame_11)
        self.frame_12.setGeometry(QtCore.QRect(0, 0, 241, 181))
        self.frame_12.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_12.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_12.setObjectName("frame_12")
        self.label_13 = QtWidgets.QLabel(self.frame_12)
        self.label_13.setGeometry(QtCore.QRect(10, 0, 121, 25))
        self.label_13.setObjectName("label_13")
        self.checkBox_20 = QtWidgets.QCheckBox(self.frame_12)
        self.checkBox_20.setGeometry(QtCore.QRect(10, 30, 96, 22))
        self.checkBox_20.setChecked(True)
        self.checkBox_20.setObjectName("checkBox_20")
        self.checkBox_21 = QtWidgets.QCheckBox(self.frame_12)
        self.checkBox_21.setGeometry(QtCore.QRect(10, 50, 101, 22))
        self.checkBox_21.setChecked(True)
        self.checkBox_21.setObjectName("checkBox_21")
        self.checkBox_22 = QtWidgets.QCheckBox(self.frame_12)
        self.checkBox_22.setGeometry(QtCore.QRect(10, 70, 111, 22))
        self.checkBox_22.setChecked(True)
        self.checkBox_22.setObjectName("checkBox_22")
        self.checkBox_23 = QtWidgets.QCheckBox(self.frame_12)
        self.checkBox_23.setGeometry(QtCore.QRect(10, 90, 111, 22))
        self.checkBox_23.setChecked(True)
        self.checkBox_23.setObjectName("checkBox_23")
        self.checkBox_24 = QtWidgets.QCheckBox(self.frame_12)
        self.checkBox_24.setGeometry(QtCore.QRect(10, 110, 96, 22))
        self.checkBox_24.setChecked(True)
        self.checkBox_24.setObjectName("checkBox_24")
        self.data_x_12 = QtWidgets.QTextEdit(self.frame_12)
        self.data_x_12.setGeometry(QtCore.QRect(130, 30, 91, 22))
        self.data_x_12.setObjectName("data_x_12")
        self.data_x_13 = QtWidgets.QTextEdit(self.frame_12)
        self.data_x_13.setGeometry(QtCore.QRect(130, 50, 91, 22))
        self.data_x_13.setObjectName("data_x_13")
        self.data_x_14 = QtWidgets.QTextEdit(self.frame_12)
        self.data_x_14.setGeometry(QtCore.QRect(130, 70, 91, 22))
        self.data_x_14.setObjectName("data_x_14")
        self.data_x_15 = QtWidgets.QTextEdit(self.frame_12)
        self.data_x_15.setGeometry(QtCore.QRect(130, 90, 91, 22))
        self.data_x_15.setObjectName("data_x_15")
        self.data_x_16 = QtWidgets.QTextEdit(self.frame_12)
        self.data_x_16.setGeometry(QtCore.QRect(130, 110, 91, 22))
        self.data_x_16.setObjectName("data_x_16")
        self.checkBox_25 = QtWidgets.QCheckBox(self.frame_12)
        self.checkBox_25.setGeometry(QtCore.QRect(10, 130, 131, 22))
        self.checkBox_25.setChecked(True)
        self.checkBox_25.setObjectName("checkBox_25")
        self.checkBox_26 = QtWidgets.QCheckBox(self.frame_12)
        self.checkBox_26.setGeometry(QtCore.QRect(10, 150, 131, 22))
        self.checkBox_26.setChecked(True)
        self.checkBox_26.setObjectName("checkBox_26")
        self.frame_13 = QtWidgets.QFrame(self.Input_5)
        self.frame_13.setGeometry(QtCore.QRect(260, 30, 241, 181))
        self.frame_13.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_13.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_13.setObjectName("frame_13")
        self.label_14 = QtWidgets.QLabel(self.frame_13)
        self.label_14.setGeometry(QtCore.QRect(10, 0, 121, 25))
        self.label_14.setObjectName("label_14")
        self.label_4 = QtWidgets.QLabel(self.frame_13)
        self.label_4.setGeometry(QtCore.QRect(20, 30, 51, 22))
        self.label_4.setObjectName("label_4")
        self.data_x_17 = QtWidgets.QTextEdit(self.frame_13)
        self.data_x_17.setGeometry(QtCore.QRect(140, 30, 91, 22))
        self.data_x_17.setObjectName("data_x_17")
        self.label_5 = QtWidgets.QLabel(self.frame_13)
        self.label_5.setGeometry(QtCore.QRect(20, 60, 81, 22))
        self.label_5.setObjectName("label_5")
        self.data_x_18 = QtWidgets.QTextEdit(self.frame_13)
        self.data_x_18.setGeometry(QtCore.QRect(140, 60, 91, 22))
        self.data_x_18.setObjectName("data_x_18")
        self.label_9 = QtWidgets.QLabel(self.frame_13)
        self.label_9.setGeometry(QtCore.QRect(20, 90, 111, 22))
        self.label_9.setObjectName("label_9")
        self.data_x_19 = QtWidgets.QTextEdit(self.frame_13)
        self.data_x_19.setGeometry(QtCore.QRect(140, 90, 91, 22))
        self.data_x_19.setObjectName("data_x_19")
        self.label_14.raise_()
        self.label_4.raise_()
        self.data_x_17.raise_()
        self.label_5.raise_()
        self.data_x_18.raise_()
        self.label_9.raise_()
        self.data_x_19.raise_()
        self.frame_21 = QtWidgets.QFrame(self.Input_5)
        self.frame_21.setGeometry(QtCore.QRect(510, 30, 111, 181))
        self.frame_21.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_21.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_21.setObjectName("frame_21")
        self.label_27 = QtWidgets.QLabel(self.frame_21)
        self.label_27.setGeometry(QtCore.QRect(10, 0, 121, 25))
        self.label_27.setObjectName("label_27")
        self.radioButton_13 = QtWidgets.QRadioButton(self.frame_21)
        self.radioButton_13.setGeometry(QtCore.QRect(20, 30, 115, 22))
        self.radioButton_13.setChecked(False)
        self.radioButton_13.setObjectName("radioButton_13")
        self.radioButton_14 = QtWidgets.QRadioButton(self.frame_21)
        self.radioButton_14.setGeometry(QtCore.QRect(20, 60, 115, 22))
        self.radioButton_14.setObjectName("radioButton_14")
        self.frame_9 = QtWidgets.QFrame(self.Train)
        self.frame_9.setGeometry(QtCore.QRect(30, 280, 661, 241))
        self.frame_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.Input_7 = QtWidgets.QGroupBox(self.frame_9)
        self.Input_7.setGeometry(QtCore.QRect(20, 10, 621, 211))
        self.Input_7.setObjectName("Input_7")
        self.frame_20 = QtWidgets.QFrame(self.Input_7)
        self.frame_20.setGeometry(QtCore.QRect(10, 60, 241, 151))
        self.frame_20.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_20.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_20.setObjectName("frame_20")
        self.label_26 = QtWidgets.QLabel(self.frame_20)
        self.label_26.setGeometry(QtCore.QRect(10, 0, 121, 25))
        self.label_26.setObjectName("label_26")
        self.label_20 = QtWidgets.QLabel(self.frame_20)
        self.label_20.setGeometry(QtCore.QRect(30, 30, 91, 22))
        self.label_20.setObjectName("label_20")
        self.label_21 = QtWidgets.QLabel(self.frame_20)
        self.label_21.setGeometry(QtCore.QRect(30, 50, 91, 22))
        self.label_21.setObjectName("label_21")
        self.label_22 = QtWidgets.QLabel(self.frame_20)
        self.label_22.setGeometry(QtCore.QRect(30, 70, 91, 22))
        self.label_22.setObjectName("label_22")
        self.label_23 = QtWidgets.QLabel(self.frame_20)
        self.label_23.setGeometry(QtCore.QRect(30, 90, 91, 22))
        self.label_23.setObjectName("label_23")
        self.label_24 = QtWidgets.QLabel(self.frame_20)
        self.label_24.setGeometry(QtCore.QRect(30, 110, 91, 22))
        self.label_24.setObjectName("label_24")
        self.data_x_33 = QtWidgets.QTextEdit(self.frame_20)
        self.data_x_33.setGeometry(QtCore.QRect(130, 30, 91, 22))
        self.data_x_33.setObjectName("data_x_33")
        self.data_x_34 = QtWidgets.QTextEdit(self.frame_20)
        self.data_x_34.setGeometry(QtCore.QRect(130, 50, 91, 22))
        self.data_x_34.setObjectName("data_x_34")
        self.data_x_35 = QtWidgets.QTextEdit(self.frame_20)
        self.data_x_35.setGeometry(QtCore.QRect(130, 70, 91, 22))
        self.data_x_35.setObjectName("data_x_35")
        self.data_x_36 = QtWidgets.QTextEdit(self.frame_20)
        self.data_x_36.setGeometry(QtCore.QRect(130, 90, 91, 22))
        self.data_x_36.setObjectName("data_x_36")
        self.data_x_37 = QtWidgets.QTextEdit(self.frame_20)
        self.data_x_37.setGeometry(QtCore.QRect(130, 110, 91, 22))
        self.data_x_37.setObjectName("data_x_37")
        self.radioButton_15 = QtWidgets.QRadioButton(self.Input_7)
        self.radioButton_15.setGeometry(QtCore.QRect(10, 30, 115, 22))
        self.radioButton_15.setChecked(False)
        self.radioButton_15.setObjectName("radioButton_15")
        self.label_21.raise_()
        self.frame_20.raise_()
        self.radioButton_15.raise_()
        self.frame_10 = QtWidgets.QFrame(self.Train)
        self.frame_10.setGeometry(QtCore.QRect(30, 540, 661, 171))
        self.frame_10.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_10.setObjectName("frame_10")
        self.Input_8 = QtWidgets.QGroupBox(self.frame_10)
        self.Input_8.setGeometry(QtCore.QRect(20, 10, 641, 151))
        self.Input_8.setObjectName("Input_8")
        self.frame_22 = QtWidgets.QFrame(self.Input_8)
        self.frame_22.setGeometry(QtCore.QRect(10, 50, 241, 101))
        self.frame_22.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_22.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_22.setObjectName("frame_22")
        self.label_28 = QtWidgets.QLabel(self.frame_22)
        self.label_28.setGeometry(QtCore.QRect(10, 0, 121, 25))
        self.label_28.setObjectName("label_28")
        self.checkBox_43 = QtWidgets.QCheckBox(self.frame_22)
        self.checkBox_43.setGeometry(QtCore.QRect(30, 30, 96, 22))
        self.checkBox_43.setObjectName("checkBox_43")
        self.checkBox_44 = QtWidgets.QCheckBox(self.frame_22)
        self.checkBox_44.setGeometry(QtCore.QRect(30, 50, 96, 22))
        self.checkBox_44.setObjectName("checkBox_44")
        self.checkBox_45 = QtWidgets.QCheckBox(self.frame_22)
        self.checkBox_45.setGeometry(QtCore.QRect(30, 70, 96, 22))
        self.checkBox_45.setObjectName("checkBox_45")
        self.checkBox_41 = QtWidgets.QCheckBox(self.Input_8)
        self.checkBox_41.setGeometry(QtCore.QRect(10, 20, 96, 22))
        self.checkBox_41.setObjectName("checkBox_41")
        self.checkBox_42 = QtWidgets.QCheckBox(self.Input_8)
        self.checkBox_42.setGeometry(QtCore.QRect(260, 20, 96, 22))
        self.checkBox_42.setObjectName("checkBox_42")
        self.frame_23 = QtWidgets.QFrame(self.Input_8)
        self.frame_23.setGeometry(QtCore.QRect(270, 50, 211, 101))
        self.frame_23.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_23.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_23.setObjectName("frame_23")
        self.label_29 = QtWidgets.QLabel(self.frame_23)
        self.label_29.setGeometry(QtCore.QRect(10, 0, 121, 25))
        self.label_29.setObjectName("label_29")
        self.radioButton_16 = QtWidgets.QRadioButton(self.frame_23)
        self.radioButton_16.setGeometry(QtCore.QRect(20, 30, 81, 22))
        self.radioButton_16.setChecked(False)
        self.radioButton_16.setObjectName("radioButton_16")
        self.radioButton_17 = QtWidgets.QRadioButton(self.frame_23)
        self.radioButton_17.setGeometry(QtCore.QRect(20, 60, 81, 22))
        self.radioButton_17.setChecked(False)
        self.radioButton_17.setObjectName("radioButton_17")
        self.radioButton_22 = QtWidgets.QRadioButton(self.frame_23)
        self.radioButton_22.setGeometry(QtCore.QRect(110, 30, 81, 22))
        self.radioButton_22.setChecked(False)
        self.radioButton_22.setObjectName("radioButton_22")
        self.radioButton_23 = QtWidgets.QRadioButton(self.frame_23)
        self.radioButton_23.setGeometry(QtCore.QRect(110, 60, 81, 22))
        self.radioButton_23.setChecked(False)
        self.radioButton_23.setObjectName("radioButton_23")
        self.frame_24 = QtWidgets.QFrame(self.Input_8)
        self.frame_24.setGeometry(QtCore.QRect(500, 50, 121, 101))
        self.frame_24.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_24.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_24.setObjectName("frame_24")
        self.label_30 = QtWidgets.QLabel(self.frame_24)
        self.label_30.setGeometry(QtCore.QRect(10, 0, 121, 25))
        self.label_30.setObjectName("label_30")
        self.radioButton_19 = QtWidgets.QRadioButton(self.frame_24)
        self.radioButton_19.setGeometry(QtCore.QRect(30, 30, 115, 22))
        self.radioButton_19.setChecked(False)
        self.radioButton_19.setObjectName("radioButton_19")
        self.radioButton_20 = QtWidgets.QRadioButton(self.frame_24)
        self.radioButton_20.setGeometry(QtCore.QRect(30, 60, 115, 22))
        self.radioButton_20.setChecked(False)
        self.radioButton_20.setObjectName("radioButton_20")
        self.save_model_2 = QtWidgets.QPushButton(self.Train)
        self.save_model_2.setGeometry(QtCore.QRect(30, 730, 80, 23))
        self.save_model_2.setObjectName("save_model_2")
        self.textBrowser = QtWidgets.QTextBrowser(self.Train)
        self.textBrowser.setGeometry(QtCore.QRect(710, 50, 431, 661))
        self.textBrowser.setObjectName("textBrowser")
        self.label_25 = QtWidgets.QLabel(self.Train)
        self.label_25.setGeometry(QtCore.QRect(710, 20, 81, 21))
        self.label_25.setObjectName("label_25")
        self.tabWidget.addTab(self.Train, "")
        self.Evaluate = QtWidgets.QWidget()
        self.Evaluate.setObjectName("Evaluate")
        self.frame_17 = QtWidgets.QFrame(self.Evaluate)
        self.frame_17.setGeometry(QtCore.QRect(30, 20, 911, 91))
        self.frame_17.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_17.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_17.setObjectName("frame_17")
        self.Input_2 = QtWidgets.QGroupBox(self.frame_17)
        self.Input_2.setGeometry(QtCore.QRect(10, 10, 891, 71))
        self.Input_2.setObjectName("Input_2")
        self.label_31 = QtWidgets.QLabel(self.Input_2)
        self.label_31.setGeometry(QtCore.QRect(20, 30, 81, 25))
        self.label_31.setObjectName("label_31")
        self.data_x_38 = QtWidgets.QTextEdit(self.Input_2)
        self.data_x_38.setGeometry(QtCore.QRect(120, 30, 301, 25))
        self.data_x_38.setObjectName("data_x_38")
        self.frame_18 = QtWidgets.QFrame(self.Evaluate)
        self.frame_18.setGeometry(QtCore.QRect(30, 120, 911, 111))
        self.frame_18.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_18.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_18.setObjectName("frame_18")
        self.Input_3 = QtWidgets.QGroupBox(self.frame_18)
        self.Input_3.setGeometry(QtCore.QRect(10, 10, 891, 91))
        self.Input_3.setObjectName("Input_3")
        self.label_32 = QtWidgets.QLabel(self.Input_3)
        self.label_32.setGeometry(QtCore.QRect(20, 30, 81, 25))
        self.label_32.setObjectName("label_32")
        self.data_x_39 = QtWidgets.QTextEdit(self.Input_3)
        self.data_x_39.setGeometry(QtCore.QRect(120, 30, 301, 25))
        self.data_x_39.setObjectName("data_x_39")
        self.label_33 = QtWidgets.QLabel(self.Input_3)
        self.label_33.setGeometry(QtCore.QRect(20, 60, 91, 25))
        self.label_33.setObjectName("label_33")
        self.data_x_40 = QtWidgets.QTextEdit(self.Input_3)
        self.data_x_40.setGeometry(QtCore.QRect(120, 60, 301, 25))
        self.data_x_40.setObjectName("data_x_40")
        self.save_model_3 = QtWidgets.QPushButton(self.Evaluate)
        self.save_model_3.setGeometry(QtCore.QRect(30, 240, 80, 23))
        self.save_model_3.setObjectName("save_model_3")
        self.tabWidget.addTab(self.Evaluate, "")

        self.retranslateUi(Dialog)
        self.tabWidget.setCurrentIndex(3)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.save_data.setText(_translate("Dialog", "Save"))
        self.Input.setTitle(_translate("Dialog", "Input"))
        self.label.setText(_translate("Dialog", "Data X"))
        self.data_x.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Sans Serif\'; font-size:9pt;\">./data/X</span></p></body></html>"))
        self.Blurring.setTitle(_translate("Dialog", "Blurring"))
        self.label_2.setText(_translate("Dialog", "Nibabel smoothing"))
        self.fwhm4.setText(_translate("Dialog", "FWHM=4"))
        self.fwhm5.setText(_translate("Dialog", "FWHM=5"))
        self.fwhm6.setText(_translate("Dialog", "FWHM=6"))
        self.fwhm7.setText(_translate("Dialog", "FWHM=7"))
        self.fwhm8.setText(_translate("Dialog", "FWHM=8"))
        self.groupBox.setTitle(_translate("Dialog", "Adjacent Slice"))
        self.label_3.setText(_translate("Dialog", "slice of images:"))
        self.slice1.setText(_translate("Dialog", "1"))
        self.slice3.setText(_translate("Dialog", "3"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Data), _translate("Dialog", "Data"))
        self.Input_4.setTitle(_translate("Dialog", "U-Net"))
        self.label_6.setText(_translate("Dialog", "Depth"))
        self.radioButton.setText(_translate("Dialog", "2"))
        self.radioButton_2.setText(_translate("Dialog", "3"))
        self.radioButton_3.setText(_translate("Dialog", "4"))
        self.radioButton_4.setText(_translate("Dialog", "5"))
        self.radioButton_5.setText(_translate("Dialog", "6"))
        self.label_7.setText(_translate("Dialog", "# of filter"))
        self.radioButton_6.setText(_translate("Dialog", "16"))
        self.radioButton_7.setText(_translate("Dialog", "32"))
        self.radioButton_8.setText(_translate("Dialog", "64"))
        self.radioButton_9.setText(_translate("Dialog", "128"))
        self.radioButton_10.setText(_translate("Dialog", "256"))
        self.label_8.setText(_translate("Dialog", "Layers"))
        self.checkBox.setText(_translate("Dialog", "Dropout"))
        self.checkBox_2.setText(_translate("Dialog", "BatchNorm"))
        self.checkBox_3.setText(_translate("Dialog", "Upconv"))
        self.checkBox_4.setText(_translate("Dialog", "Maxpool"))
        self.checkBox_5.setText(_translate("Dialog", "Residual"))
        self.save_model.setText(_translate("Dialog", "Save"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Model), _translate("Dialog", "Model"))
        self.Input_5.setTitle(_translate("Dialog", "Data-related"))
        self.label_11.setText(_translate("Dialog", "Augmentation-2D"))
        self.checkBox_6.setText(_translate("Dialog", "Rotation"))
        self.checkBox_7.setText(_translate("Dialog", "Shear"))
        self.checkBox_8.setText(_translate("Dialog", "Shift-width"))
        self.checkBox_9.setText(_translate("Dialog", "Shift-height"))
        self.checkBox_10.setText(_translate("Dialog", "Zoom"))
        self.data_x_2.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Sans Serif\'; font-size:9pt;\">15</span></p></body></html>"))
        self.data_x_3.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Sans Serif\'; font-size:9pt;\">30</span></p></body></html>"))
        self.data_x_4.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Sans Serif\'; font-size:9pt;\">0.33</span></p></body></html>"))
        self.data_x_5.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Sans Serif\'; font-size:9pt;\">0.33</span></p></body></html>"))
        self.data_x_6.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Sans Serif\'; font-size:9pt;\">0.33</span></p></body></html>"))
        self.checkBox_11.setText(_translate("Dialog", "Flip-horizontal"))
        self.checkBox_12.setText(_translate("Dialog", "Flip-Vertical"))
        self.label_13.setText(_translate("Dialog", "Augmentation-2D"))
        self.checkBox_20.setText(_translate("Dialog", "Rotation"))
        self.checkBox_21.setText(_translate("Dialog", "Shear"))
        self.checkBox_22.setText(_translate("Dialog", "Shift-width"))
        self.checkBox_23.setText(_translate("Dialog", "Shift-height"))
        self.checkBox_24.setText(_translate("Dialog", "Zoom"))
        self.data_x_12.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Sans Serif\'; font-size:9pt;\">15</span></p></body></html>"))
        self.data_x_13.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Sans Serif\'; font-size:9pt;\">30</span></p></body></html>"))
        self.data_x_14.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Sans Serif\'; font-size:9pt;\">0.33</span></p></body></html>"))
        self.data_x_15.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Sans Serif\'; font-size:9pt;\">0.33</span></p></body></html>"))
        self.data_x_16.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Sans Serif\'; font-size:9pt;\">0.33</span></p></body></html>"))
        self.checkBox_25.setText(_translate("Dialog", "Flip-horizontal"))
        self.checkBox_26.setText(_translate("Dialog", "Flip-Vertical"))
        self.label_14.setText(_translate("Dialog", "Parameters"))
        self.label_4.setText(_translate("Dialog", "Epoch"))
        self.data_x_17.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Sans Serif\'; font-size:9pt;\">400</span></p></body></html>"))
        self.label_5.setText(_translate("Dialog", "Batch size"))
        self.data_x_18.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Sans Serif\'; font-size:9pt;\">5</span></p></body></html>"))
        self.label_9.setText(_translate("Dialog", "Validation ratio"))
        self.data_x_19.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Sans Serif\'; font-size:9pt;\">0.25</span></p></body></html>"))
        self.label_27.setText(_translate("Dialog", "Loss function"))
        self.radioButton_13.setText(_translate("Dialog", "L2 loss"))
        self.radioButton_14.setText(_translate("Dialog", "L1 loss"))
        self.Input_7.setTitle(_translate("Dialog", "Optimizer"))
        self.label_26.setText(_translate("Dialog", "Adam"))
        self.label_20.setText(_translate("Dialog", "learning rate"))
        self.label_21.setText(_translate("Dialog", "decay"))
        self.label_22.setText(_translate("Dialog", "epsilon"))
        self.label_23.setText(_translate("Dialog", "beta_1"))
        self.label_24.setText(_translate("Dialog", "beta_2"))
        self.data_x_33.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Sans Serif\'; font-size:9pt;\">1e-5</span></p></body></html>"))
        self.data_x_34.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Sans Serif\'; font-size:9pt;\">0.0</span></p></body></html>"))
        self.data_x_35.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Sans Serif\'; font-size:9pt;\">1e-8</span></p></body></html>"))
        self.data_x_36.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Sans Serif\'; font-size:9pt;\">0.9</span></p></body></html>"))
        self.data_x_37.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Sans Serif\'; font-size:9pt;\">0.99</span></p></body></html>"))
        self.radioButton_15.setText(_translate("Dialog", "Adam"))
        self.Input_8.setTitle(_translate("Dialog", "Save"))
        self.label_28.setText(_translate("Dialog", "Tensorboard"))
        self.checkBox_43.setText(_translate("Dialog", "graph"))
        self.checkBox_44.setText(_translate("Dialog", "grads"))
        self.checkBox_45.setText(_translate("Dialog", "images"))
        self.checkBox_41.setText(_translate("Dialog", "Logs"))
        self.checkBox_42.setText(_translate("Dialog", "models"))
        self.label_29.setText(_translate("Dialog", "Models-monitor"))
        self.radioButton_16.setText(_translate("Dialog", "L2 loss"))
        self.radioButton_17.setText(_translate("Dialog", "L1 loss"))
        self.radioButton_22.setText(_translate("Dialog", "SSIM"))
        self.radioButton_23.setText(_translate("Dialog", "PSNR"))
        self.label_30.setText(_translate("Dialog", "Models-mode"))
        self.radioButton_19.setText(_translate("Dialog", "Max"))
        self.radioButton_20.setText(_translate("Dialog", "Min"))
        self.save_model_2.setText(_translate("Dialog", "Start"))
        self.label_25.setText(_translate("Dialog", "Progress"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Train), _translate("Dialog", "Train"))
        self.Input_2.setTitle(_translate("Dialog", "Model"))
        self.label_31.setText(_translate("Dialog", "Model path"))
        self.data_x_38.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Sans Serif\'; font-size:9pt;\">./saved_model/</span></p></body></html>"))
        self.Input_3.setTitle(_translate("Dialog", "Data"))
        self.label_32.setText(_translate("Dialog", "Data path"))
        self.data_x_39.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Sans Serif\'; font-size:9pt;\">./data_eval/</span></p></body></html>"))
        self.label_33.setText(_translate("Dialog", "Output path"))
        self.data_x_40.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Sans Serif\'; font-size:9pt;\">./output_eval/</span></p></body></html>"))
        self.save_model_3.setText(_translate("Dialog", "Start"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Evaluate), _translate("Dialog", "Evaluate"))

